name: Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
      - name: BEFORE
        run: |
          echo "=== BEFORE ==="
          cat /Users/rihardsindars/python-github-actions/dir_server/app.py

      - name: COPY DEV -> SERVER
        run: |
          cp /Users/rihardsindars/python-github-actions/dir_dev/app.py /Users/rihardsindars/python-github-actions/dir_server/app.py

      - name: AFTER
        run: |
          echo "=== AFTER ==="
          cat /Users/rihardsindars/python-github-actions/dir_server/app.py

      - name: RUN
        run: |
          echo "=== OUTPUT ==="
          python3 /Users/rihardsindars/python-github-actions/dir_server/app.py