name: Run Python with second repo

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Clone second repo
        run: git clone https://github.com/Rihardssss/python-client.git

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python
        run: python server/app.py
