name: Python CI

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Copy dev to server
        run: cp dir_dev/app.py dir_server/app.py

      - name: Run Python
        run: python3 dir_server/app.py
